name: NASA Project CI
on:
  push:
    branches: [master]
  pull-request:
    branches: [master]
jobs:
  build:
    runs-on: [ubuntu-latest, windows-latest]
  steps:
    -uses: actions/checkout@v2
    -name: Setting up node
    -uses: actions/setup-node@v2
    with:
      node-version: "18.14.0"
    -run: npm install
    -run: npm run build --prefix client