name: NASA Project CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: [ubuntu-latest, windows-latest]
  steps:
    -uses: actions/checkout@v2
    -name: Setting up node
    uses: actions/setup-node@v2
    with:
      node-version: "18.14.0"

    -name: Install packages
    run: npm install

    -name: Build frontend
    run: npm run build --prefix client